In [3]:
import numpy as np
import plotly.graph_objects as go

In [4]:
# Hours - Aggressive - Baseline - Conservative - Intermediate
arbitrage_data = np.array(([6,8,10,12,16,24,36,48],[12799726,13441301,13762252,13883364,14053930,14232512,14301973,14305210],[7882707,8257431,8435378,8490723,8565539,8641794,8667037,8670533],[7263117,7607782,7771381,7822853,7892757,7964427,7987715,7990566],[12598158,13232253,13551734,13674643,13848054,14031411,14103180,14106431]))
print(arbitrage_data[0])
np.save('data/arbitrage_data.npy',arbitrage_data)

[ 6  8 10 12 16 24 36 48]


In [5]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=arbitrage_data[0],y=arbitrage_data[1],mode='lines',name='Aggressive'))
fig.add_trace(go.Scatter(x=arbitrage_data[0],y=arbitrage_data[2],mode='lines',name='Base Case'))
fig.add_trace(go.Scatter(x=arbitrage_data[0],y=arbitrage_data[3],mode='lines',name='Conservative'))
fig.add_trace(go.Scatter(x=arbitrage_data[0],y=arbitrage_data[4],mode='lines',name='Intermediate'))
fig.update_layout(
    xaxis_title = 'Storage Hours',
    yaxis_title = 'Income (USD)',
)
fig.show()

In [6]:
arbitrage_datas = np.load('data/arbitrage_data.npy')
print(arbitrage_datas)

[[       6        8       10       12       16       24       36       48]
 [12799726 13441301 13762252 13883364 14053930 14232512 14301973 14305210]
 [ 7882707  8257431  8435378  8490723  8565539  8641794  8667037  8670533]
 [ 7263117  7607782  7771381  7822853  7892757  7964427  7987715  7990566]
 [12598158 13232253 13551734 13674643 13848054 14031411 14103180 14106431]]


In [7]:
etes_charge = np.load('data/echogen_charge.npy')
etes_discharge = np.load('data/echogen_discharge.npy')
etes_battery_state = np.zeros(shape=8760)

for i in range(0,8760):
    etes_battery_state[i] = (etes_charge[i]-etes_discharge[i])/100000

print(etes_battery_state[0:48])
np.save('data/echogen_battery_state.npy',etes_battery_state)

[ 1.          1.          1.          1.          1.          1.
  1.          0.          0.         -1.         -1.         -1.
  0.          0.          0.         -0.40986108 -1.         -1.
 -1.         -1.         -1.         -1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          0.          0.          0.         -0.26969524  0.
  0.          0.          0.          0.          0.         -1.
 -1.         -1.         -1.          0.          1.          1.        ]


In [8]:
import pandas as pd
data = {'Model Code':['P-EF-LT','P-EFCF-LT','E-2022'],
    'Model Owner':['PMRR','PMRR','Echogen'],
    'Charge Rate':['1.7 Php/kWh','3.88 Php/kWh','WESM'],
    'Duration':['2022-2045','2022-2045','2022'],
    }
model_summary = pd.DataFrame(data)
model_summary.style.hide_index()
model_summary.head()

Model Code Model Owner   Charge Rate   Duration
0    P-EF-LT        PMRR   1.7 Php/kWh  2022-2045
1  P-EFCF-LT        PMRR  3.88 Php/kWh  2022-2045
2     E-2022     Echogen          WESM       2022

In [9]:
table2022 = {'Model':[1,2,3,4,5],
    'Model Code':['E','E-EF','E-EFCF','P-EF','P-EFCF'],
    'Simulated by':['Echogen','PMRR','PMRR','PMRR','PMRR'],
    'Charge Rate':['WESM Rate','1.7 Php/kWh','3.88 kWh','1.7 Php/kWh','3.88 Php/kWh']
}
model2022 = pd.DataFrame(table2022)
model2022.head()

Model Model Code Simulated by   Charge Rate
0      1          E      Echogen     WESM Rate
1      2       E-EF         PMRR   1.7 Php/kWh
2      3     E-EFCF         PMRR      3.88 kWh
3      4       P-EF         PMRR   1.7 Php/kWh
4      5     P-EFCF         PMRR  3.88 Php/kWh

In [10]:
results2022 = pd.read_csv('data/model2022.csv',header=0)
results2022.head()

Model Code Schedule     WESM Case Charging Rate    Income     Cost  \
0     E-WESM  Echogen  Conservative     WESM Rate   9337.17  7112.31   
1     E-WESM  Echogen     Base Case     WESM Rate  10199.87  7696.78   
2     E-WESM  Echogen  Intermediate     WESM Rate  13102.24  6636.70   
3     E-WESM  Echogen    Aggressive     WESM Rate  13376.05  6811.31   
4       E-EF  Echogen  Conservative           1.7   9337.17  5587.90   

   Profit PHP  Profit USD  
0     2224.86   46.632991  
1     2503.09   52.464682  
2     6465.54  135.517502  
3     6564.74  137.596730  
4     3749.27   78.584573

In [11]:
print(results2022[results2022['Model Code']=='E-EF'].loc[:,'WESM Case'])
print(results2022[results2022['Model Code']=='E-EF'].loc[:,'Profit PHP'])
print(results2022[results2022['Model Code']=='P-EF'].loc[:,'WESM Case'])
print(results2022[results2022['Model Code']=='P-EF'].loc[:,'Profit PHP'])






4    Conservative
5       Base Case
6    Intermediate
7      Aggressive
Name: WESM Case, dtype: object
4    3749.27
5    4611.97
6    7514.34
7    7788.15
Name: Profit PHP, dtype: float64
12    Conservative
13       Base Case
14    Intermediate
15      Aggressive
Name: WESM Case, dtype: object
12    4517.42
13    5467.66
14    7333.66
15    7627.92
Name: Profit PHP, dtype: float64


In [12]:
fig = go.Figure()
model2022codes = ['E-WESM','E-EF','E-EFCF','P-EF','P-EFCF']
model2022colors = ['red','orange','yellow','blue','purple']
for i in range(0,len(model2022codes)):
    fig.add_trace(go.Scatter(
        x=results2022[results2022['Model Code']==model2022codes[i]].loc[:,'WESM Case'],
        y=results2022[results2022['Model Code']==model2022codes[i]].loc[:,'Profit PHP'],
        name = model2022codes[i],
        ))
fig.update_layout(
    xaxis_title='2022 Data Set',
    title = '2022 Model Data Results',
    title_x = 0.5,
    yaxis_title = 'Profit(Php/kWh)',
    legend = dict(
        title='Model Code'
    )
)
fig.show()

In [13]:
cutoff_results = np.load('data/cutoff_results.npy')
heatmapdata = np.zeros(shape=(11,4))
print(len(cutoff_results))
i=0
for x in range(0,4):
    for y in range(0,11):
        heatmapdata[y,x] = round(cutoff_results[i,4],2)
        i=i+1


44


In [14]:
import plotly.figure_factory as ff

x=['Conservative','Base Case','Intermediate','Aggresive']
y = []
for i in range(0,11):
    string = 4.0+(i*0.2)
    y.append(str(string)) 
print(y)
fig = ff.create_annotated_heatmap(heatmapdata,x=x,y=y,
    colorscale='RdBu',showscale=False)
fig.update_layout(
    title = 'Profit (Php/kW) for WESM Charging with Cutoff',
    title_x = 0.5,
    yaxis_title='Cutoff Rate (Php/kWh)',
    xaxis_title='2022 Dataset',
    legend_title='Profit (Php)',
)
fig.update_xaxes(
    side = 'bottom' 
)
fig.update_yaxes(
    dtick = 0.2
)
fig.show()

['4.0', '4.2', '4.4', '4.6', '4.8', '5.0', '5.2', '5.4', '5.6', '5.8', '6.0']


In [15]:

fig.show()

In [16]:
modelLT = pd.read_csv('data/modelLT.csv')
print(modelLT.iloc[:,0:4])

   Model   Model Code Charging Rate Discharging Mode
0      1     P-ADJ-EF   1.7 Php/kWh         Adjacent
1      2   P-ADJ-EFCF  3.88 Php/kWh         Adjacent
2      3    P-NADJ-EF   1.7 Php/kWh     Non-Adjacent
3      4  P-NADJ-EFCF  3.88 Php/kWh     Non-Adjacent
4      5       P-WESM          WESM     Non-Adjacent
5      6         E-LT          WESM     Non-Adjacent


In [17]:
fig = go.Figure()
fig.add_trace(go.Bar(x=modelLT['Model Code'],y=modelLT['Cost'],name='Charging Cost'))
fig.add_trace(go.Bar(x=modelLT['Model Code'],y=modelLT['Income'],name='Income'))
fig.add_trace(go.Bar(x=modelLT['Model Code'],y=modelLT['Profit'],name ='Profit'))
fig.update_layout(
    title='Results for Long Term Simulations',
    title_x=0.5,
    xaxis_title='Model',
    yaxis_title='Value (Php/kW)',
    legend = dict(
        orientation='h',
        yanchor = 'bottom',
        y = 1,
        xanchor='center',
        x = 0.5
    )
)
fig.show()

In [48]:

model2022 = {'Model':[1,2,3,4,5,6,7,8],
'Description':['Echogen schedule using WESM rates for charging & discharging','Echogen schedule using BTM Energy Fee as charging rate','Echogen schedule using BTM Energy Fee and Capacity fee as charging rate','PMRR schedule using BTM Energy Fee as charging rate','PMRR schedule using BTM Energy Fee and Capacity fee as charging rate','PMRR schedule using WESM rates for charging & discharging','PMRR schedule using WESM rates for charging & discharging with minimum WESM rate during discharging','Echogen results from R. Wackerly'],
'Model Code':['E-WESM','E-EF','E-EFCF','P-EF','P-EFCF','P-WESM-U','P-WESM-C','E-WESM-RW'],
'Simulated by':['PMRR','PMRR','PMRR','PMRR','PMRR','PMRR','PMRR','Echogen-RW'],
'Charge Rate':['WESM Rate','1.7 Php/kWh','3.88 Php/kWh','1.7 Php/kWh','3.88 Php/kWh','WESM','WESM Constrained','WESM']
}
table2022 = pd.DataFrame(model2022)
fig = go.Figure(data=go.Table(
    header=dict(values=list(table2022.columns)),
    cells =dict(values=[table2022['Model'],table2022['Description'],table2022['Model Code'],table2022['Simulated by'],table2022['Charge Rate']],),
))
fig.update_layout(
)
fig.show()